[package]
name = "scrum-poker"
version = "0.1.0"
authors = ["sebsoto <sebsoto@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.7"
serde = "1.0.126"
serde_json = "1.0"
